#!/bin/bash -e

export K8S_ENDPOINT="${K8S_ENDPOINT:-http://k8s.ai-traders.com:8080}"
echo "Using K8S_ENDPOINT=${K8S_ENDPOINT}"

mkdir -p "${ide_home}/.kube"
cat <<EOF >${ide_home}/.kube/config
# this file was generated by running:
# root@cluster1-k8s-node-1a:/home/ubuntu# kubectl config set-cluster default-cluster --server=${K8S_ENDPOINT}
# root@cluster1-k8s-node-1a:/home/ubuntu# kubectl config set-context default-system --cluster=default-cluster
# root@cluster1-k8s-node-1a:/home/ubuntu# kubectl config use-context default-system
# and it was saved as ~/.kube/config
apiVersion: v1
clusters:
- cluster:
    server: ${K8S_ENDPOINT}
  name: default-cluster
contexts:
- context:
    cluster: default-cluster
    user: ""
  name: default-system
current-context: default-system
kind: Config
preferences: {}
users: []
EOF

chown ide:ide -R "${ide_home}/.kube/"
