pipelines:
  docker-k8s-ide:
    group: k8s
    label_template: "${git[:8]}"
    materials:
      git:
        git: "git@git.ai-traders.com:k8s/docker-k8s-ide.git"
        branch: master
        blacklist:
          - "**/*.md"
    stages:
      - build:
          clean_workspace: true
          jobs:
            build:
              resources:
                - docker_builder
              artifacts:
                - build:
                    source: image/imagerc
                    destination:
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks verify_version
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ops_docker_push=true ./tasks build
      - itest:
          clean_workspace: true
          jobs:
            itest:
              resources:
                - docker_builder
              tasks:
                - fetch:
                    stage: build
                    job: build
                    is_file: yes
                    source: imagerc
                    destination: image/
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks itest
      - release:
          clean_workspace: true
          jobs:
            code:
              resources:
                - docker_builder
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks release
      - publish:
          clean_workspace: true
          jobs:
            docker_image:
              resources:
                - docker_builder
              tasks:
                - fetch:
                    stage: build
                    job: build
                    is_file: yes
                    source: imagerc
                    destination: image/
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks publish
